apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rima-gif/k8s-manifests.git'
    targetRevision: main
    path: backend
    directory:
      recurse: true  # Pour traiter tous les fichiers YAML du dossier
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend  # Assurez-vous que ce namespace existe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  # Crée automatiquement le namespace si absent
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rima-gif/k8s-manifests.git'
    targetRevision: main
    path: frontend
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
