apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.backend.svc.cluster.local:3306/BankDB
  SPRING_DATASOURCE_USERNAME: root
